# Imports

In [10]:
import os
import sys
import time
import dotenv
import numpy as np
import pandas as pd

print("Python version: {}". format(sys.version))
print("NumPy version: {}". format(np.__version__))
print("pandas version: {}". format(pd.__version__))

import warnings
warnings.filterwarnings('ignore')
print('-'*25)

Python version: 3.13.5 (main, Jun 12 2025, 12:22:43) [Clang 20.1.4 ]
NumPy version: 2.4.4
pandas version: 3.0.2
-------------------------

In [11]:
dotenv.load_dotenv("../.env")

True

In [ ]:
from pydantic import SecretStr
from langchain.chat_models import init_chat_model
from langchain_openai import OpenAIEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings
from langchain_community.document_loaders import CSVLoader, TextLoader
from langchain_core.vectorstores import InMemoryVectorStore
from langchain_qdrant import QdrantVectorStore

# 1.0 Load data

In [13]:
DATA_FILE_PATH = "../data/medquad.csv"

In [14]:
med_df = pd.read_csv(DATA_FILE_PATH)

med_df.head()

,question,answer,source,focus_area
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea...",NIHSeniorHealth,Glaucoma
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...,NIHSeniorHealth,Glaucoma
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma

In [15]:
# Checking NULL values
display(med_df.isnull().sum())

question       0
answer         5
source         0
focus_area    14
dtype: int64

In [16]:
print(len(med_df))
med_df.dropna(axis=0, inplace=True)
print(len(med_df))

16412
16393

In [17]:
focus_areas = med_df['focus_area'].unique().tolist()
focus_areas.sort()
focus_areas

['11-beta-hydroxylase deficiency',
 '15q11.2 microdeletion',
 '15q13.3 microdeletion',
 '15q13.3 microdeletion syndrome',
 '15q13.3 microduplication syndrome',
 '15q24 microdeletion',
 '16p11.2 deletion syndrome',
 '16q24.3 microdeletion syndrome',
 '17 alpha-hydroxylase/17,20-lyase deficiency',
 '17-alpha-hydroxylase deficiency',
 '17-beta hydroxysteroid dehydrogenase 3 deficiency',
 '17q23.1q23.2 microdeletion syndrome',
 '18 Hydroxylase deficiency',
 '18q deletion syndrome',
 '19p13.12 microdeletion syndrome',
 '1p36 deletion syndrome',
 '1q21.1 microdeletion',
 '1q21.1 microdeletion syndrome',
 '1q44 microdeletion syndrome',
 '2,4-Dienoyl-CoA reductase deficiency',
 '2-hydroxyglutaric aciduria',
 '2-methyl-3-hydroxybutyric aciduria',
 '2-methylbutyryl-CoA dehydrogenase deficiency',
 '2009 H1N1 Flu',
 '20p12.3 microdeletion syndrome',
 '21-hydroxylase deficiency',
 '22q11.2 deletion syndrome',
 '22q11.2 duplication',
 '22q11.2 duplication syndrome',
 '22q13.3 deletion syndrome',
 '2q37 deletion syndrome',
 '3 alpha methylcrotonyl-CoA carboxylase 2 deficiency',
 '3 methylglutaconic aciduria type V',
 '3-Hydroxyisobutyric aciduria',
 '3-M syndrome',
 '3-beta-hydroxysteroid dehydrogenase deficiency',
 '3-hydroxy-3-methylglutaryl-CoA lyase deficiency',
 '3-hydroxyacyl-CoA dehydrogenase deficiency',
 '3-methylcrotonyl-CoA carboxylase deficiency',
 '3-methylglutaconyl-CoA hydratase deficiency',
 '3MC syndrome',
 '4 Steps to Manage Your Diabetes for Life',
 '46,XX testicular disorder of sex development',
 '47 XXX syndrome',
 '47, XYY syndrome',
 '47,XYY syndrome',
 '48,XXYY syndrome',
 '49,XXXXX syndrome',
 '5-alpha reductase deficiency',
 '5q minus syndrome',
 '5q- syndrome',
 '5q14.3 microdeletion syndrome',
 '6q24-related transient neonatal diabetes mellitus',
 '7q11.23 duplication syndrome',
 '8p11 myeloproliferative syndrome',
 '8p23.1 duplication syndrome',
 '8q12 microduplication syndrome',
 '9q22.3 microdeletion',
 'A1C',
 'ABCD syndrome',
 'ACTH-independent macronodular adrenal hyperplasia',
 'ADCY5-related dyskinesia',
 'ADNP syndrome',
 'ADULT syndrome',
 'AIDS-Related Lymphoma',
 'AL amyloidosis',
 'ALG1-congenital disorder of glycosylation',
 'ALG12-congenital disorder of glycosylation',
 'ALG6-congenital disorder of glycosylation',
 'ARDS',
 'Aarskog-Scott syndrome',
 'Abdominal Adhesions',
 'Abdominal Pain',
 'Abdominal aortic aneurysm',
 'Aberrant subclavian artery',
 'Abetalipoproteinemia',
 'Ablepharon macrostomia syndrome',
 'Abortion',
 'Abruzzo Erickson syndrome',
 'Abscess',
 'Absence of Tibia',
 'Absence of the Septum Pellucidum',
 'Absent patella',
 'Acanthamoeba - Granulomatous Amebic Encephalitis (GAE); Keratitis',
 'Acanthoma',
 'Acanthosis nigricans muscle cramps acral enlargement',
 'Acatalasemia',
 'Accessory deep peroneal nerve',
 'Accessory navicular bone',
 'Aceruloplasminemia',
 'Achalasia',
 'Achard syndrome',
 'Achondrogenesis',
 'Achondrogenesis type 1A',
 'Achondrogenesis type 2',
 'Achondroplasia',
 'Achondroplasia and Swiss type agammaglobulinemia',
 'Achondroplasia and severe combined immunodeficiency',
 'Achromatopsia 3',
 'Acid Lipase Disease',
 'Acinetobacter in Healthcare Settings',
 'Acne',
 'Acoustic Neuroma',
 'Acquired Cystic Kidney Disease',
 'Acquired hemophilia',
 'Acquired hemophilia A',
 'Acquired pure red cell aplasia',
 'Acrocallosal syndrome, Schinzel type',
 'Acrocapitofemoral dysplasia',
 'Acrocephalopolydactylous dysplasia',
 'Acrodermatitis enteropathica',
 'Acrodysplasia scoliosis',
 'Acrofacial dysostosis Catania type',
 'Acrokeratoelastoidosis of Costa',
 'Acromegaloid changes, cutis verticis gyrata and corneal leukoma',
 'Acromegaloid facial appearance syndrome',
 'Acromegaly',
 'Acromesomelic dysplasia',
 'Acromesomelic dysplasia Hunter Thompson type',
 'Acromesomelic dysplasia Maroteaux type',
 'Acroosteolysis dominant type',
 'Acrorenal mandibular syndrome',
 'Actinomycosis',
 'Acupuncture',
 'Acute Bronchitis',
 'Acute Disseminated Encephalomyelitis',
 'Acute Lymphocytic Leukemia',
 'Acute Myeloid Leukemia',
 'Acute alcohol sensitivity',
 'Acute febrile neutrophilic dermatosis',
 'Acute intermittent porphyria',
 'Acute respiratory distress syndrome',
 'Acute zonal occult outer retinopathy',
 'Adams-Oliver syndrome',
 'Addison Disease',
 'Adenoameloblastoma',
 'Adenocarcinoma of the appendix',
 'Adenoid cystic carcinoma',
 'Adenylosuccinase deficiency',
 'Adhesions',
 'Adiposis dolorosa',
 'Adolescent idiopathic scoliosis',
 'Adoption',
 'Adrenal Gland Cancer',
 'Adrenal Gland Disorders',
 "Adrenal Insufficiency and Addison's Disease",
 'Adrenocortical carcinoma',
 'Adrenoleukodystrophy',
 'Adult Acute Lymphoblastic Leukemia',
 'Adult Acute Myeloid Leukemia',
 'Adult Central Nervous System Tumors',
 'Adult Hodgkin Lymphoma',
 'Adult Non-Hodgkin Lymphoma',
 'Adult Primary Liver Cancer',
 'Adult Soft Tissue Sarcoma',
 'Adult neuronal ceroid lipofuscinosis',
 "Adult-onset Still's disease",
 'Adult-onset vitelliform macular dystrophy',
 'Advance Directives',
 'Afibrinogenemia',
 'African American Health',
 'African iron overload',
 'After Surgery',
 'Agammaglobulinemia, non-Bruton type',
 'Aganglionosis, total intestinal',
 'Age-related Macular Degeneration',
 'Agenesis of the Corpus Callosum',
 'Agenesis of the dorsal pancreas',
 'Agnosia',
 'Aicardi Syndrome',
 'Aicardi syndrome',
 'Aicardi-Goutieres Syndrome Disorder',
 'Aicardi-Goutieres syndrome',
 'Aicardi-Goutieres syndrome type 1',
 'Aicardi-Goutieres syndrome type 2',
 'Aicardi-Goutieres syndrome type 3',
 'Aicardi-Goutieres syndrome type 4',
 'Aicardi-Goutieres syndrome type 5',
 'Ainhum',
 'Air Pollution',
 'Akesson syndrome',
 'Al Gazali Sabrinathan Nair syndrome',
 'Alagille Syndrome',
 'Alagille syndrome',
 'Alaninuria with microcephaly, dwarfism, enamel hypoplasia and diabetes mellitus',
 "Albright's hereditary osteodystrophy",
 'Alcohol',
 'Alcohol Use and Older Adults',
 'Alcoholism and Alcohol Abuse',
 'Alexander Disease',
 'Alexander disease',
 'Alkhurma Hemorrhagic Fever (AHF)',
 'Allan-Herndon-Dudley syndrome',
 'Allergy',
 'Alopecia areata',
 'Alopecia epilepsy oligophrenia syndrome of Moynahan',
 'Alopecia intellectual disability syndrome 2',
 'Alopecia macular degeneration growth retardation',
 'Alopecia totalis',
 'Alopecia universalis',
 'Alopecia, epilepsy, pyorrhea, mental subnormality',
 'Alopecia-intellectual disability syndrome',
 "Alpers' Disease",
 'Alpers-Huttenlocher syndrome',
 'Alpha-1 Antitrypsin Deficiency',
 'Alpha-1 antitrypsin deficiency',
 'Alpha-ketoglutarate dehydrogenase deficiency',
 'Alpha-mannosidosis type 1',
 'Alpha-thalassemia',
 'Alpha-thalassemia x-linked intellectual disability syndrome',
 'Alport syndrome',
 'Alstrm syndrome',
 'Alternating Hemiplegia',
 'Alveolar capillary dysplasia',
 'Alzheimer disease',
 "Alzheimer's Caregivers",
 "Alzheimer's Caregiving",
 "Alzheimer's Disease",
 'Am I at Risk for Type 2 Diabetes? Taking Steps to Lower Your Risk of Getting Diabetes',
 'Amaurosis congenita cone-rod type with congenital hypertrichosis',
 'Amblyopia',
 'Ambras syndrome',
 'Amelogenesis imperfecta',
 'Amelogenesis imperfecta local hypoplastic',
 'Amelogenesis imperfecta nephrocalcinosis',
 'Amelogenesis imperfecta, hypoplastic/hypomaturation, X-linked 2',
 'Ameloonychohypohidrotic syndrome',
 'Amino aciduria with mental deficiency, dwarfism, muscular dystrophy, osteoporosis and acidosis',
 'Amish infantile epilepsy syndrome',
 'Amish lethal microcephaly',
 'Amniotic band syndrome',
 'Amyloidosis',
 'Amyloidosis AA',
 'Amyloidosis and Kidney Disease',
 'Amyloidosis corneal',
 'Amyloidosis familial visceral',
 'Amyopathic dermatomyositis',
 'Amyotonia congenita',
 'Amyotrophic Lateral Sclerosis',
 'Amyotrophic lateral sclerosis',
 'Amyotrophic lateral sclerosis type 6',
 'Amyotrophic lateral sclerosis-parkinsonism/dementia complex 1',
 'Anabolic Steroids',
 'Anal Cancer',
 'Anal Disorders',
 'Anal sphincter dysplasia',
 'Analgesic Nephropathy (Painkillers and the Kidneys)',
 'Anaphylaxis',
 'Anaplasmosis',
 'Anaplastic astrocytoma',
 'Anaplastic ganglioglioma',
 'Anatomy',
 'Anauxetic dysplasia',
 'Andermann syndrome',
 'Andersen-Tawil syndrome',
 'Androgen insensitivity syndrome',
 'Anemia',
 'Anemia due to Adenosine triphosphatase deficiency',
 'Anemia in Chronic Kidney Disease',
 'Anemia of Inflammation and Chronic Disease',
 'Anemia sideroblastic and spinocerebellar ataxia',
 'Anencephaly',
 'Anencephaly and spina bifida X-linked',
 'Anesthesia',
 'Aneurysm',
 'Aneurysms',
 'Angel shaped phalangoepiphyseal dysplasia',
 'Angelman Syndrome',
 'Angelman syndrome',
 'Angina',
 'Angioma serpiginosum, autosomal dominant',
 'Angiomatosis, diffuse corticomeningeal, of Divry and Van Bogaert',
 'Angioplasty',
 'Animal Bites',
 'Animal Diseases and Your Health',
 'Aniridia',
 'Aniridia absent patella',
 'Ankle Injuries and Disorders',
 'Ankyloblepharon filiforme imperforate anus',
 'Ankylosing Spondylitis',
 'Ankylosing spondylitis',
 'Ankylosis of teeth',
 'Annular atrophic lichen planus',
 'Annular pancreas',
 'Anonychia congenita',
 'Anonychia-onychodystrophy with hypoplasia or absence of distal phalanges',
 'Anophthalmia plus syndrome',
 'Anophthalmos with limb anomalies',
 'Antecubital pterygium',
 'Anterior polar cataract 2',
 'Anterior segment mesenchymal dysgenesis',
 'Anthrax',
 'Anti-plasmin deficiency, congenital',
 'Antibiotic Resistance',
 'Antibiotics',
 'Antidepressants',
 'Antioxidants',
 'Antiphospholipid Antibody Syndrome',
 'Antiphospholipid Syndrome',
 'Antisynthetase syndrome',
 'Antley Bixler syndrome',
 'Anxiety',
 'Anxiety Disorders',
 'Aortic Aneurysm',
 'Aortic arch anomaly - peculiar facies - intellectual disability',
 'Apert syndrome',
 'Aphalangia partial with syndactyly and duplication of metatarsal IV',
 'Aphasia',
 'Aplasia cutis congenita',
 'Aplasia cutis congenita intestinal lymphangiectasia',
 'Aplasia cutis congenita of limbs recessive',
 'Aplastic Anemia',
 'Apocrine carcinoma',
 'Apparent mineralocorticoid excess',
 'Appendicitis',
 'Apraxia',
 'Aquagenic pruritus',
 'Arachnodactyly - intellectual disability - dysmorphism',
 'Arachnoid Cysts',
 'Arachnoiditis',
 'Arginase deficiency',
 'Arm Injuries and Disorders',
 'Aromatase excess syndrome',
 'Aromatic L-amino acid decarboxylase deficiency',
 'Arrhythmia',
 'Arsenic',
 'Arteriovenous Malformation',
 'Arteriovenous Malformations',
 'Arthritis',
 'Arthrogryposis like disorder',
 'Arthrogryposis renal dysfunction cholestasis syndrome',
 'Arthrogryposis, distal, type 2E',
 'Arthrogryposis, distal, with hypopituitarism, intellectual disability and facial anomalies',
 'Artificial Limbs',
 'Arts syndrome',
 'Asbestos',
 'Asbestos-Related Lung Diseases',
 'Ascher Syndrome',
 'Asian American Health',
 'Asperger Syndrome',
 'Asperger syndrome',
 'Aspergillosis',
 'Assisted Living',
 'Assisted Reproductive Technology',
 'Assistive Devices',
 'Asthma',
 'Asthma in Children',
 'Ataxia',
 'Ataxia - hypogonadism - choroidal dystrophy',
 'Ataxia Telangiectasia',
 'Ataxia telangiectasia',
 'Ataxia with Oculomotor Apraxia Type 2',
 'Atelosteogenesis type 1',
 'Athabaskan brainstem dysgenesis',
 'Atherosclerosis',
 "Athlete's Foot",
 'Atrial Fibrillation',
 'Atrial Fibrillation and Stroke',
 'Atrial myxoma, familial',
 'Atrial septal defect ostium primum',
 'Attention Deficit Hyperactivity Disorder',
 'Attention Deficit-Hyperactivity Disorder',
 'Atypical Chronic Myelogenous Leukemia',
 'Atypical hemolytic uremic syndrome',
 'Auriculo-condylar syndrome',
 'Ausems Wittebol-Post Hennekam syndrome',
 'Autism',
 'Autism Spectrum Disorder',
 'Autoimmune Diseases',
 'Autoimmune Hepatitis',
 'Autoimmune atrophic gastritis',
 'Autoimmune autonomic ganglionopathy',
 'Autoimmune gastrointestinal dysmotility',
 'Autoimmune hemolytic anemia',
 'Autoimmune hepatitis',
 'Autoimmune myocarditis',
 'Autoimmune pancreatitis',
 'Autoimmune polyglandular syndrome type 1',
 'Autonomic Nervous System Disorders',
 'Autosomal dominant caf au lait spots',
 'Autosomal dominant compelling helio ophthalmic outburst syndrome',
 'Autosomal dominant deafness-onychodystrophy syndrome',
 'Autosomal dominant intermediate Charcot-Marie-Tooth disease type A',
 'Autosomal dominant intermediate Charcot-Marie-Tooth disease type B',
 'Autosomal dominant intermediate Charcot-Marie-Tooth disease type C',
 'Autosomal dominant intermediate Charcot-Marie-Tooth disease type D',
 'Autosomal dominant intermediate Charcot-Marie-Tooth disease type E',
 'Autosomal dominant intermediate Charcot-Marie-Tooth disease type F',
 'Autosomal dominant neuronal ceroid lipofuscinosis 4B',
 'Autosomal dominant nocturnal frontal lobe epilepsy',
 'Autosomal dominant optic atrophy and cataract',
 'Autosomal dominant optic atrophy plus syndrome',
 'Autosomal dominant partial epilepsy with auditory features',
 'Autosomal recessive Charcot-Marie-Tooth disease with hoarseness',
 'Autosomal recessive axonal neuropathy with neuromyotonia',
 'Autosomal recessive hyper IgE syndrome',
 'Autosomal recessive nonsyndromic congenital nuclear cataract',
 'Autosomal recessive optic atrophy, hearing loss, and peripheral neuropathy',
 'Autosomal recessive palmoplantar keratoderma and congenital alopecia',
 'Autosomal recessive polycystic kidney disease',
 'Autosomal recessive pseudohypoaldosteronism type 1',
 'Autosomal recessive spastic ataxia 4',
 'Axenfeld-Rieger syndrome',
 'Axenfeld-Rieger syndrome type 1',
 'Axenfeld-Rieger syndrome type 2',
 'Axial osteomalacia',
 'Axial spondylometaphyseal dysplasia',
 'B Vitamins',
 'BOD syndrome',
 'BRCA1 hereditary breast and ovarian cancer syndrome',
 'BRCA2 hereditary breast and ovarian cancer syndrome',
 'Baby Health Checkup',
 'Back Injuries',
 'Back Pain',
 'Bacterial Infections',
 'Bad Breath',
 'Balance Problems',
 'Baller-Gerold syndrome',
 'Bamforth syndrome',
 'Bangstad syndrome',
 'Banki syndrome',
 'Bannayan-Riley-Ruvalcaba syndrome',
 'Bantu siderosis',
 'Baraitser Brett Piesowicz syndrome',
 'Baraitser-Winter syndrome',
 'Barber Say syndrome',
 'Bardet-Biedl syndrome',
 'Bardet-Biedl syndrome 10',
 'Bardet-Biedl syndrome 11',
 'Bardet-Biedl syndrome 12',
 'Bardet-Biedl syndrome 2',
 'Bardet-Biedl syndrome 5',
 'Bardet-Biedl syndrome 6',
 'Bardet-Biedl syndrome 7',
 'Bardet-Biedl syndrome 8',
 'Bardet-Biedl syndrome 9',
 'Bare lymphocyte syndrome',
 'Bare lymphocyte syndrome 2',
 'Barotrauma',
 'Barraquer-Simons syndrome',
 'Barrett esophagus',
 'Bart-Pumphrey syndrome',
 'Barth Syndrome',
 'Barth syndrome',
 'Bartter syndrome',
 'Bartter syndrome antenatal type 1',
 'Bartter syndrome antenatal type 2',
 'Bartter syndrome type 3',
 'Basilar migraine',
 'Battaglia-Neri syndrome',
 'Batten Disease',
 'Baylisascaris infection',
 'Beardwell syndrome',
 'Beare-Stevenson cutis gyrata syndrome',
 'Beckwith-Wiedemann syndrome',
 'Bedbugs',
 'Bednar tumor',
 'Bedwetting',
 "Behcet's Disease",
 "Behcet's Syndrome",
 "Behcet's disease",
 'Behet disease',
 'Behr syndrome',
 "Bell's Palsy",
 "Bell's palsy",
 'Benign Essential Blepharospasm',
 'Benign Tumors',
 'Benign familial neonatal-infantile seizures',
 'Benign hereditary chorea',
 'Benign multicystic peritoneal mesothelioma',
 'Benign paroxysmal positional vertigo',
 'Benign recurrent intrahepatic cholestasis',
 'Benign rolandic epilepsy (BRE)',
 'Benign schwannoma',
 'Bereavement',
 'Beriberi',
 'Berry aneurysm, cirrhosis, pulmonary emphysema, and cerebral calcification',
 'Best vitelliform macular dystrophy',
 'Beta ketothiolase deficiency',
 'Beta-thalassemia',
 'Bethlem myopathy',
 'Beukes familial hip dysplasia',
 'Bietti crystalline corneoretinal dystrophy',
 'Bietti crystalline dystrophy',
 'Bifid nose with or without anorectal and renal anomalies',
 'Bilateral frontal polymicrogyria',
 'Bilateral frontoparietal polymicrogyria',
 'Bilateral generalized polymicrogyria',
 'Bilateral perisylvian polymicrogyria',
 'Bile Duct Cancer',
 'Bile Duct Cancer (Cholangiocarcinoma)',
 'Bile Duct Diseases',
 'Bile acid synthesis defect, congenital, 4',
 'Biliary Atresia',
 "Binswanger's Disease",
 "Binswanger's disease",
 'Biodefense and Bioterrorism',
 'Biopsy',
 'Biotin-thiamine-responsive basal ganglia disease',
 'Biotinidase deficiency',
 'Bipolar Disorder',
 'Bird Flu',
 'Birdshot chorioretinopathy',
 'Birt-Hogg-Dub syndrome',
 'Birt-Hogg-Dube syndrome',
 'Birth Control',
 'Birth Defects',
 'Birth Weight',
 'Birthmarks',
 'Bixler Christian Gorlin syndrome',
 'Bjornstad syndrome',
 'Bjrnstad syndrome',
 'Bladder Cancer',
 'Bladder Diseases',
 'Bladder cancer',
 'Blastomycosis',
 'Blau syndrome',
 'Bleeding',
 'Bleeding Disorders',
 'Blepharophimosis with ptosis, syndactyly, and short stature',
 'Blepharophimosis, ptosis, and epicanthus inversus syndrome type 1',
 'Blepharophimosis, ptosis, and epicanthus inversus syndrome type 2',
 'Blepharoptosis myopia ectopia lentis',
 'Blepharospasm',
 'Blood',
 'Blood Clots',
 'Blood Count Tests',
 'Blood Disorders',
 'Blood Pressure Medicines',
 'Blood Sugar',
 'Blood Thinners',
 'Blood Transfusion and Donation',
 'Bloom syndrome',
 'Blount disease',
 'Blue cone monochromatism',
 'Blue rubber bleb nevus syndrome',
 'Bobble-head doll syndrome',
 'Body Weight',
 'Bone Cancer',
 'Bone Density',
 'Bone Diseases',
 'Bone Grafts',
 'Bone Infections',
 'Bone Marrow Diseases',
 'Bone Marrow Transplantation',
 'Bone dysplasia lethal Holmgren type',
 'Book syndrome',
 'Boomerang dysplasia',
 'Borjeson-Forssman-Lehmann syndrome',
 'Bork Stender Schmidt syndrome',
 'Botox',
 'Botulism',
 'Bowel Incontinence',
 'Bowel Movement',
 'Bowen syndrome',
 'Bowen-Conradi syndrome',
 'Brachial Plexus Injuries',
 'Brachycephalofrontonasal dysplasia',
 'Brachydactyly Mononen type',
 'Brachydactyly type A1',
 'Brachydactyly type A2',
 'Brachydactyly type A4',
 'Brachydactyly type A5',
 'Brachydactyly type A6',
 'Brachydactyly type B',
 'Brachydactyly type C',
 'Brachydactyly types B and E combined',
 'Brachyolmia',
 'Brachyolmia type 3',
 'Brain Aneurysm',
 'Brain Diseases',
 'Brain Malformations',
 'Brain Tumors',
 'Brain and Spinal Tumors',
 'Branchial arch syndrome X-linked',
 'Branchiooculofacial syndrome',
 'Branchiootorenal syndrome',
 'Breast Cancer',
 'Breast Diseases',
 'Breast Reconstruction',
 'Breastfeeding',
 'Breathing Problems',
 'Brittle cornea syndrome',
 'Brittle diabetes',
 'Brody myopathy',
 'Broken Heart Syndrome',
 'Bronchial Disorders',
 'Bronchiectasis',
 'Bronchiolitis obliterans',
 'Bronchiolitis obliterans organizing pneumonia',
 'Bronchitis',
 'Bronchopulmonary Dysplasia',
 'Brooke-Spiegler syndrome',
 'Brooks Wisniewski Brown syndrome',
 'Brown syndrome',
 'Brown-Sequard Syndrome',
 'Brown-Sequard syndrome',
 'Brugada syndrome',
 'Brugada syndrome 4',
 'Bruises',
 'Budd-Chiari syndrome',
 'Buerger disease',
 'Bullying',
 'Burn-Mckeown syndrome',
 'Burns',
 'Bursitis',
 'Buschke Lowenstein tumor',
 'Buschke Ollendorff syndrome',
 'Buschke-Ollendorff syndrome',
 'C syndrome',
 'C1q deficiency',
 'C1q nephropathy',
 'C3 glomerulopathy',
 'CADASIL',
 'CASK-related intellectual disability',
 'CATSPER1-related nonsyndromic male infertility',
 'CAV3-related distal myopathy',
 'CDKL5-related disorder',
 'CHARGE syndrome',
 'CHILD syndrome',
 'CHMP2B-related frontotemporal dementia',
 'CHOPS syndrome',
 'CHST3-related skeletal dysplasia',
 'CLOVES syndrome',
 'COACH syndrome',
 'COASY Protein-Associated Neurodegeneration',
 'CODAS syndrome',
 'COG5-congenital disorder of glycosylation',
 'COL4A1-related brain small-vessel disease',
 'COPD',
 'CPR',
 'CREST syndrome',
 'CT Scans',
 'Caffeine',
 'Caffey disease',
 'Calciphylaxis',
 'Calcium',
 'Campomelia Cumming type',
 'Camptobrachydactyly',
 'Camptocormism',
 'Camptodactyly arthropathy coxa vara pericarditis syndrome',
 'Camptodactyly syndrome Guadalajara type 1',
 'Camptodactyly syndrome Guadalajara type 3',
 'Camptodactyly taurinuria',
 'Campylobacter Infections',
 'Camurati Engelmann disease, type 2',
 'Camurati-Engelmann disease',
 'Canavan Disease',
 'Canavan disease',

# 2.0 Retrieval Augmented Generation

I want to stick to a RAG with a narrow focus on Nutrition.

In [ ]:
llm = init_chat_model("gpt-4o-mini", model_provider="openai")
embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

# llm = init_chat_model(
#     "google_genai:" + "gemini-2.5-flash-lite",
#     model_provider="google_genai",
#     api_key=os.environ['GOOGLE_API_KEY']
# )
# embeddings = GoogleGenerativeAIEmbeddings(
#     model="gemini-embedding-001",
#     api_key=SecretStr(os.environ['GOOGLE_API_KEY']),
# )

In [ ]:
# with open('./focus_areas.txt', 'w') as f:
#     f.write("\n".join(focus_areas))

# docs = TextLoader('./focus_areas.txt').load()
# print(docs[:2])

df = pd.DataFrame.from_dict({'focus_area': focus_areas})
df.to_csv('../data/focus_areas.csv', index=False)
docs = CSVLoader('../data/focus_areas.csv').load()
print(docs[:5])

[Document(metadata={'source': './focus_areas.csv', 'row': 0}, page_content='focus_area: 11-beta-hydroxylase deficiency'), Document(metadata={'source': './focus_areas.csv', 'row': 1}, page_content='focus_area: 15q11.2 microdeletion'), Document(metadata={'source': './focus_areas.csv', 'row': 2}, page_content='focus_area: 15q13.3 microdeletion'), Document(metadata={'source': './focus_areas.csv', 'row': 3}, page_content='focus_area: 15q13.3 microdeletion syndrome'), Document(metadata={'source': './focus_areas.csv', 'row': 4}, page_content='focus_area: 15q13.3 microduplication syndrome')]

In [ ]:
vector_store = InMemoryVectorStore.from_documents(docs, embeddings)

Let's use Vector Embeddings to collect the focus areas we want i.e. those topics most semantically similar to Nutrition.

In [18]:
docs = vector_store.similarity_search("Nutrition", k=150)
for doc in docs:
    print(doc)

page_content='focus_area: Nutrition' metadata={'source': './focus_areas.csv', 'row': 2978}
page_content='focus_area: Nutrition for Seniors' metadata={'source': './focus_areas.csv', 'row': 2981}
page_content='focus_area: Nutritional Support' metadata={'source': './focus_areas.csv', 'row': 2982}
page_content='focus_area: Child Nutrition' metadata={'source': './focus_areas.csv', 'row': 793}
page_content='focus_area: Toddler Nutrition' metadata={'source': './focus_areas.csv', 'row': 4093}
page_content='focus_area: Malnutrition' metadata={'source': './focus_areas.csv', 'row': 2540}
page_content='focus_area: Nutrition for Advanced Chronic Kidney Disease in Adults' metadata={'source': './focus_areas.csv', 'row': 2979}
page_content='focus_area: Nutrition for Early Chronic Kidney Disease in Adults' metadata={'source': './focus_areas.csv', 'row': 2980}
page_content='focus_area: Pregnancy and Nutrition' metadata={'source': './focus_areas.csv', 'row': 3387}
page_content='focus_area: Infant and Newborn Nutrition' metadata={'source': './focus_areas.csv', 'row': 2117}
page_content='focus_area: Diabetic Diet' metadata={'source': './focus_areas.csv', 'row': 1193}
page_content='focus_area: Dietary Proteins' metadata={'source': './focus_areas.csv', 'row': 1213}
page_content='focus_area: Dietary Fiber' metadata={'source': './focus_areas.csv', 'row': 1212}
page_content='focus_area: Vitamins' metadata={'source': './focus_areas.csv', 'row': 4276}
page_content='focus_area: Vegetarian Diet' metadata={'source': './focus_areas.csv', 'row': 4251}
page_content='focus_area: DASH Diet' metadata={'source': './focus_areas.csv', 'row': 1106}
page_content='focus_area: Diets' metadata={'source': './focus_areas.csv', 'row': 1215}
page_content='focus_area: Eating Disorders' metadata={'source': './focus_areas.csv', 'row': 1322}
page_content='focus_area: Dietary Fats' metadata={'source': './focus_areas.csv', 'row': 1211}
page_content='focus_area: Obesity' metadata={'source': './focus_areas.csv', 'row': 2986}
page_content='focus_area: Dietary Supplements' metadata={'source': './focus_areas.csv', 'row': 1214}
page_content='focus_area: Weight Control' metadata={'source': './focus_areas.csv', 'row': 4313}
page_content='focus_area: Vitamin A' metadata={'source': './focus_areas.csv', 'row': 4271}
page_content='focus_area: Healthy Living' metadata={'source': './focus_areas.csv', 'row': 1833}
page_content='focus_area: Healthy Aging' metadata={'source': './focus_areas.csv', 'row': 1832}
page_content='focus_area: Prevent diabetes problems: Keep your nervous system healthy' metadata={'source': './focus_areas.csv', 'row': 3409}
page_content='focus_area: Vitamin C' metadata={'source': './focus_areas.csv', 'row': 4272}
page_content='focus_area: Metabolic Disorders' metadata={'source': './focus_areas.csv', 'row': 2656}
page_content='focus_area: B Vitamins' metadata={'source': './focus_areas.csv', 'row': 407}
page_content='focus_area: Folic Acid' metadata={'source': './focus_areas.csv', 'row': 1572}
page_content='focus_area: Obesity in Children' metadata={'source': './focus_areas.csv', 'row': 2988}
page_content='focus_area: Food Labeling' metadata={'source': './focus_areas.csv', 'row': 1575}
page_content='focus_area: Vitamin D' metadata={'source': './focus_areas.csv', 'row': 4273}
page_content='focus_area: Food Allergy' metadata={'source': './focus_areas.csv', 'row': 1574}
page_content='focus_area: Antioxidants' metadata={'source': './focus_areas.csv', 'row': 296}
page_content='focus_area: Overweight and Obesity' metadata={'source': './focus_areas.csv', 'row': 3106}
page_content='focus_area: Breastfeeding' metadata={'source': './focus_areas.csv', 'row': 580}
page_content='focus_area: Kidney Failure: Eat Right to Feel Right on Hemodialysis' metadata={'source': './focus_areas.csv', 'row': 2267}
page_content='focus_area: Iron-Deficiency Anemia' metadata={'source': './focus_areas.csv', 'row': 2170}
page_content='focus_area: Digestive Diseases' metadata={'source': './focus_areas.csv', 'row': 1224}
page_content='focus_area: Vitamin E' metadata={'source': './focus_areas.csv', 'row': 4274}
page_content='focus_area: Seniors' Health' metadata={'source': './focus_areas.csv', 'row': 3727}
page_content='focus_area: Fluid and Electrolyte Balance' metadata={'source': './focus_areas.csv', 'row': 1566}
page_content='focus_area: What I need to know about Physical Activity and Diabetes' metadata={'source': './focus_areas.csv', 'row': 4348}
page_content='focus_area: Metabolic Panel' metadata={'source': './focus_areas.csv', 'row': 2657}
page_content='focus_area: Vitamin K' metadata={'source': './focus_areas.csv', 'row': 4275}
page_content='focus_area: Malabsorption Syndromes' metadata={'source': './focus_areas.csv', 'row': 2529}
page_content='focus_area: Exercise and Physical Fitness' metadata={'source': './focus_areas.csv', 'row': 1427}
page_content='focus_area: Diabetes, Heart Disease, and Stroke' metadata={'source': './focus_areas.csv', 'row': 1192}
page_content='focus_area: Diabetes' metadata={'source': './focus_areas.csv', 'row': 1182}
page_content='focus_area: Food Safety' metadata={'source': './focus_areas.csv', 'row': 1576}
page_content='focus_area: School Health' metadata={'source': './focus_areas.csv', 'row': 3703}
page_content='focus_area: Health Literacy' metadata={'source': './focus_areas.csv', 'row': 1827}
page_content='focus_area: Weight Loss Surgery' metadata={'source': './focus_areas.csv', 'row': 4314}
page_content='focus_area: Osteoporosis' metadata={'source': './focus_areas.csv', 'row': 3084}
page_content='focus_area: Insulin Resistance and Prediabetes' metadata={'source': './focus_areas.csv', 'row': 2144}
page_content='focus_area: College Health' metadata={'source': './focus_areas.csv', 'row': 946}
page_content='focus_area: Diabetes Type 2' metadata={'source': './focus_areas.csv', 'row': 1187}
page_content='focus_area: Metabolic Syndrome' metadata={'source': './focus_areas.csv', 'row': 2658}
page_content='focus_area: Foodborne Illness' metadata={'source': './focus_areas.csv', 'row': 1577}
page_content='focus_area: Blood Sugar' metadata={'source': './focus_areas.csv', 'row': 529}
page_content='focus_area: Carnosinemia' metadata={'source': './focus_areas.csv', 'row': 679}
page_content='focus_area: 4 Steps to Manage Your Diabetes for Life' metadata={'source': './focus_areas.csv', 'row': 41}
page_content='focus_area: Anemia' metadata={'source': './focus_areas.csv', 'row': 256}
page_content='focus_area: Pernicious Anemia' metadata={'source': './focus_areas.csv', 'row': 3252}
page_content='focus_area: Stomach Disorders' metadata={'source': './focus_areas.csv', 'row': 3943}
page_content='focus_area: Lactose Intolerance' metadata={'source': './focus_areas.csv', 'row': 2322}
page_content='focus_area: Diabetes in Children and Teens' metadata={'source': './focus_areas.csv', 'row': 1189}
page_content='focus_area: Toddler Health' metadata={'source': './focus_areas.csv', 'row': 4092}
page_content='focus_area: Prevent diabetes problems: Keep your eyes healthy' metadata={'source': './focus_areas.csv', 'row': 3405}
page_content='focus_area: What I need to know about Lactose Intolerance' metadata={'source': './focus_areas.csv', 'row': 4345}
page_content='focus_area: Anemia of Inflammation and Chronic Disease' metadata={'source': './focus_areas.csv', 'row': 259}
page_content='focus_area: Teen Health' metadata={'source': './focus_areas.csv', 'row': 4024}
page_content='focus_area: Swallowing Disorders' metadata={'source': './focus_areas.csv', 'row': 3975}
page_content='focus_area: Sports Fitness' metadata={'source': './focus_areas.csv', 'row': 3916}
page_content='focus_area: Foodborne Illnesses' metadata={'source': './focus_areas.csv', 'row': 1578}
page_content='focus_area: Prevent diabetes problems: Keep your mouth healthy' metadata={'source': './focus_areas.csv', 'row': 3408}
page_content='focus_area: Obesity Hypoventilation Syndrome' metadata={'source': './focus_areas.csv', 'row': 2987}
page_content='focus_area: Prevent diabetes problems: Keep your heart and blood vessels healthy' metadata={'source': './focus_areas.csv', 'row': 3406}
page_content='focus_area: Dental Health' metadata={'source': './focus_areas.csv', 'row': 1154}
page_content='focus_area: Prediabetes' metadata={'source': './focus_areas.csv', 'row': 3384}
page_content='focus_area: Phenylketonuria' metadata={'source': './focus_areas.csv', 'row': 3271}
page_content='focus_area: What I need to know about Living with Kidney Failure' metadata={'source': './focus_areas.csv', 'row': 4346}
page_content='focus_area: Small Intestine Disorders' metadata={'source': './focus_areas.csv', 'row': 3797}
page_content='focus_area: Carbohydrates' metadata={'source': './focus_areas.csv', 'row': 658}
page_content='focus_area: Body Weight' metadata={'source': './focus_areas.csv', 'row': 537}
page_content='focus_area: Your Guide to Diabetes: Type 1 and Type 2' metadata={'source': './focus_areas.csv', 'row': 4431}
page_content='focus_area: Hormones' metadata={'source': './focus_areas.csv', 'row': 1971}
page_content='focus_area: Rickets' metadata={'source': './focus_areas.csv', 'row': 3626}
page_content='focus_area: Pet Health' metadata={'source': './focus_areas.csv', 'row': 3262}
page_content='focus_area: Glutamine deficiency, congenital' metadata={'source': './focus_areas.csv', 'row': 1716}
page_content='focus_area: Peptidic growth factors deficiency' metadata={'source': './focus_areas.csv', 'row': 3238}
page_content='focus_area: Bone Density' metadata={'source': './focus_areas.csv', 'row': 539}
page_content='focus_area: Health Occupations' metadata={'source': './focus_areas.csv', 'row': 1828}
page_content='focus_area: Dehydration' metadata={'source': './focus_areas.csv', 'row': 1143}
page_content='focus_area: Diabetes Type 1' metadata={'source': './focus_areas.csv', 'row': 1186}
page_content='focus_area: Diagnosis of Diabetes and Prediabetes' metadata={'source': './focus_areas.csv', 'row': 1204}
page_content='focus_area: Tooth Decay' metadata={'source': './focus_areas.csv', 'row': 4098}
page_content='focus_area: Celiac Disease' metadata={'source': './focus_areas.csv', 'row': 704}
page_content='focus_area: Prevent diabetes problems: Keep your diabetes under control' metadata={'source': './focus_areas.csv', 'row': 3404}
page_content='focus_area: Children's Health' metadata={'source': './focus_areas.csv', 'row': 823}
page_content='focus_area: What I need to know about Gestational Diabetes' metadata={'source': './focus_areas.csv', 'row': 4337}
page_content='focus_area: Prevent diabetes problems: Keep your kidneys healthy' metadata={'source': './focus_areas.csv', 'row': 3407}
page_content='focus_area: Diabetes and Pregnancy' metadata={'source': './focus_areas.csv', 'row': 1188}
page_content='focus_area: Monitor Your Diabetes' metadata={'source': './focus_areas.csv', 'row': 2740}
page_content='focus_area: Diabetes Complications' metadata={'source': './focus_areas.csv', 'row': 1183}
page_content='focus_area: Juvenile osteoporosis' metadata={'source': './focus_areas.csv', 'row': 2219}
page_content='focus_area: Sleep Deprivation and Deficiency' metadata={'source': './focus_areas.csv', 'row': 3792}
page_content='focus_area: Fatigue' metadata={'source': './focus_areas.csv', 'row': 1521}
page_content='focus_area: Feingold syndrome' metadata={'source': './focus_areas.csv', 'row': 1526}
page_content='focus_area: Health Screening' metadata={'source': './focus_areas.csv', 'row': 1830}
page_content='focus_area: Calcium' metadata={'source': './focus_areas.csv', 'row': 636}
page_content='focus_area: Gluten Sensitivity' metadata={'source': './focus_areas.csv', 'row': 1721}
page_content='focus_area: Anemia in Chronic Kidney Disease' metadata={'source': './focus_areas.csv', 'row': 258}
page_content='focus_area: Health Checkup' metadata={'source': './focus_areas.csv', 'row': 1822}
page_content='focus_area: Primary carnitine deficiency' metadata={'source': './focus_areas.csv', 'row': 3421}
page_content='focus_area: Preconception Care' metadata={'source': './focus_areas.csv', 'row': 3383}
page_content='focus_area: I Can Lower My Risk for Type 2 Diabetes: A Guide for American Indians' metadata={'source': './focus_areas.csv', 'row': 2058}
page_content='focus_area: Diabetes mellitus type 1' metadata={'source': './focus_areas.csv', 'row': 1191}
page_content='focus_area: Heart Diseases--Prevention' metadata={'source': './focus_areas.csv', 'row': 1842}
page_content='focus_area: What I need to know about Preparing for Pregnancy if I Have Diabetes' metadata={'source': './focus_areas.csv', 'row': 4349}
page_content='focus_area: Evaluating Health Information' metadata={'source': './focus_areas.csv', 'row': 1423}
page_content='focus_area: lactose intolerance' metadata={'source': './focus_areas.csv', 'row': 4835}
page_content='focus_area: Native American Health' metadata={'source': './focus_areas.csv', 'row': 2873}
page_content='focus_area: Health Statistics' metadata={'source': './focus_areas.csv', 'row': 1831}
page_content='focus_area: Health Fraud' metadata={'source': './focus_areas.csv', 'row': 1825}
page_content='focus_area: Growth Disorders' metadata={'source': './focus_areas.csv', 'row': 1758}
page_content='focus_area: Environmental Health' metadata={'source': './focus_areas.csv', 'row': 1382}
page_content='focus_area: Beriberi' metadata={'source': './focus_areas.csv', 'row': 475}
page_content='focus_area: Sodium' metadata={'source': './focus_areas.csv', 'row': 3813}
page_content='focus_area: Skin Aging' metadata={'source': './focus_areas.csv', 'row': 3785}
page_content='focus_area: Endocrine Diseases' metadata={'source': './focus_areas.csv', 'row': 1375}
page_content='focus_area: Animal Diseases and Your Health' metadata={'source': './focus_areas.csv', 'row': 274}
page_content='focus_area: Am I at Risk for Type 2 Diabetes? Taking Steps to Lower Your Risk of Getting Diabetes' metadata={'source': './focus_areas.csv', 'row': 218}
page_content='focus_area: Hypolipoproteinemia' metadata={'source': './focus_areas.csv', 'row': 2035}
page_content='focus_area: Insulin-like growth factor I deficiency' metadata={'source': './focus_areas.csv', 'row': 2145}
page_content='focus_area: Fetal Health and Development' metadata={'source': './focus_areas.csv', 'row': 1532}
page_content='focus_area: phenylketonuria' metadata={'source': './focus_areas.csv', 'row': 4964}
page_content='focus_area: High Blood Cholesterol' metadata={'source': './focus_areas.csv', 'row': 1937}
page_content='focus_area: Infant and Newborn Development' metadata={'source': './focus_areas.csv', 'row': 2116}
page_content='focus_area: Transient neonatal diabetes mellitus' metadata={'source': './focus_areas.csv', 'row': 4122}
page_content='focus_area: Monogenic Forms of Diabetes: Neonatal Diabetes Mellitus and Maturity-onset Diabetes of the Young' metadata={'source': './focus_areas.csv', 'row': 2744}
page_content='focus_area: Childhood hypophosphatasia' metadata={'source': './focus_areas.csv', 'row': 820}
page_content='focus_area: Cholesterol' metadata={'source': './focus_areas.csv', 'row': 833}
page_content='focus_area: Infant and Newborn Care' metadata={'source': './focus_areas.csv', 'row': 2115}
page_content='focus_area: Diabetic Kidney Disease' metadata={'source': './focus_areas.csv', 'row': 1197}
page_content='focus_area: Nausea and Vomiting' metadata={'source': './focus_areas.csv', 'row': 2875}
page_content='focus_area: Hormone Replacement Therapy' metadata={'source': './focus_areas.csv', 'row': 1970}
page_content='focus_area: What I need to know about Diarrhea' metadata={'source': './focus_areas.csv', 'row': 4333}
page_content='focus_area: Vital Signs' metadata={'source': './focus_areas.csv', 'row': 4270}

In [19]:
topics_chosen = [doc.page_content.split("focus_area: ")[1] for doc in docs]
topics_chosen

['Nutrition',
 'Nutrition for Seniors',
 'Nutritional Support',
 'Child Nutrition',
 'Toddler Nutrition',
 'Malnutrition',
 'Nutrition for Advanced Chronic Kidney Disease in Adults',
 'Nutrition for Early Chronic Kidney Disease in Adults',
 'Pregnancy and Nutrition',
 'Infant and Newborn Nutrition',
 'Diabetic Diet',
 'Dietary Proteins',
 'Dietary Fiber',
 'Vitamins',
 'Vegetarian Diet',
 'DASH Diet',
 'Diets',
 'Eating Disorders',
 'Dietary Fats',
 'Obesity',
 'Dietary Supplements',
 'Weight Control',
 'Vitamin A',
 'Healthy Living',
 'Healthy Aging',
 'Prevent diabetes problems: Keep your nervous system healthy',
 'Vitamin C',
 'Metabolic Disorders',
 'B Vitamins',
 'Folic Acid',
 'Obesity in Children',
 'Food Labeling',
 'Vitamin D',
 'Food Allergy',
 'Antioxidants',
 'Overweight and Obesity',
 'Breastfeeding',
 'Kidney Failure: Eat Right to Feel Right on Hemodialysis',
 'Iron-Deficiency Anemia',
 'Digestive Diseases',
 'Vitamin E',
 "Seniors' Health",
 'Fluid and Electrolyte Balance',
 'What I need to know about Physical Activity and Diabetes',
 'Metabolic Panel',
 'Vitamin K',
 'Malabsorption Syndromes',
 'Exercise and Physical Fitness',
 'Diabetes, Heart Disease, and Stroke',
 'Diabetes',
 'Food Safety',
 'School Health',
 'Health Literacy',
 'Weight Loss Surgery',
 'Osteoporosis',
 'Insulin Resistance and Prediabetes',
 'College Health',
 'Diabetes Type 2',
 'Metabolic Syndrome',
 'Foodborne Illness',
 'Blood Sugar',
 'Carnosinemia',
 '4 Steps to Manage Your Diabetes for Life',
 'Anemia',
 'Pernicious Anemia',
 'Stomach Disorders',
 'Lactose Intolerance',
 'Diabetes in Children and Teens',
 'Toddler Health',
 'Prevent diabetes problems: Keep your eyes healthy',
 'What I need to know about Lactose Intolerance',
 'Anemia of Inflammation and Chronic Disease',
 'Teen Health',
 'Swallowing Disorders',
 'Sports Fitness',
 'Foodborne Illnesses',
 'Prevent diabetes problems: Keep your mouth healthy',
 'Obesity Hypoventilation Syndrome',
 'Prevent diabetes problems: Keep your heart and blood vessels healthy',
 'Dental Health',
 'Prediabetes',
 'Phenylketonuria',
 'What I need to know about Living with Kidney Failure',
 'Small Intestine Disorders',
 'Carbohydrates',
 'Body Weight',
 'Your Guide to Diabetes: Type 1 and Type 2',
 'Hormones',
 'Rickets',
 'Pet Health',
 'Glutamine deficiency, congenital',
 'Peptidic growth factors deficiency',
 'Bone Density',
 'Health Occupations',
 'Dehydration',
 'Diabetes Type 1',
 'Diagnosis of Diabetes and Prediabetes',
 'Tooth Decay',
 'Celiac Disease',
 'Prevent diabetes problems: Keep your diabetes under control',
 "Children's Health",
 'What I need to know about Gestational Diabetes',
 'Prevent diabetes problems: Keep your kidneys healthy',
 'Diabetes and Pregnancy',
 'Monitor Your Diabetes',
 'Diabetes Complications',
 'Juvenile osteoporosis',
 'Sleep Deprivation and Deficiency',
 'Fatigue',
 'Feingold syndrome',
 'Health Screening',
 'Calcium',
 'Gluten Sensitivity',
 'Anemia in Chronic Kidney Disease',
 'Health Checkup',
 'Primary carnitine deficiency',
 'Preconception Care',
 'I Can Lower My Risk for Type 2 Diabetes: A Guide for American Indians',
 'Diabetes mellitus type 1',
 'Heart Diseases--Prevention',
 'What I need to know about Preparing for Pregnancy if I Have Diabetes',
 'Evaluating Health Information',
 'lactose intolerance',
 'Native American Health',
 'Health Statistics',
 'Health Fraud',
 'Growth Disorders',
 'Environmental Health',
 'Beriberi',
 'Sodium',
 'Skin Aging',
 'Endocrine Diseases',
 'Animal Diseases and Your Health',
 'Am I at Risk for Type 2 Diabetes? Taking Steps to Lower Your Risk of Getting Diabetes',
 'Hypolipoproteinemia',
 'Insulin-like growth factor I deficiency',
 'Fetal Health and Development',
 'phenylketonuria',
 'High Blood Cholesterol',
 'Infant and Newborn Development',
 'Transient neonatal diabetes mellitus',
 'Monogenic Forms of Diabetes: Neonatal Diabetes Mellitus and Maturity-onset Diabetes of the Young',
 'Childhood hypophosphatasia',
 'Cholesterol',
 'Infant and Newborn Care',
 'Diabetic Kidney Disease',
 'Nausea and Vomiting',
 'Hormone Replacement Therapy',
 'What I need to know about Diarrhea',
 'Vital Signs']

In [20]:
with open('../data/topics_chosen.txt', 'w') as f:
    f.write("\n".join(topics_chosen))

Narrow down the original Q & A dataset to only include these 150 topics similar/related to Nutrition.

In [21]:
small_med_df = med_df[med_df['focus_area'].isin(topics_chosen)]
small_med_df

,question,answer,source,focus_area
103,What is (are) Diabetes ?,Too Much Glucose in the Blood Diabetes means y...,NIHSeniorHealth,Diabetes
104,Who is at risk for Diabetes? ?,"Diabetes is a serious, life-long disease. It c...",NIHSeniorHealth,Diabetes
105,How to prevent Diabetes ?,The two most common forms of diabetes are type...,NIHSeniorHealth,Diabetes
106,What are the symptoms of Diabetes ?,"Diabetes is often called a ""silent"" disease be...",NIHSeniorHealth,Diabetes
107,What are the treatments for Diabetes ?,"Diabetes cannot be cured, but it can be manage...",NIHSeniorHealth,Diabetes
...,...,...,...,...
16320,How to diagnose What I need to know about Diar...,"To find the cause of diarrhea, the health care...",NIDDK,What I need to know about Diarrhea
16321,What are the treatments for What I need to kno...,"Diarrhea is treated by replacing lost fluids, ...",NIDDK,What I need to know about Diarrhea
16322,What to do for What I need to know about Diarr...,"To prevent dehydration when you have diarrhea,...",NIDDK,What I need to know about Diarrhea
16323,How to prevent What I need to know about Diarr...,Two types of diarrhea can be preventedrotaviru...,NIDDK,What I need to know about Diarrhea
16324,What to do for What I need to know about Diarr...,"- Diarrhea is frequent, loose, and watery bowe...",NIDDK,What I need to know about Diarrhea

Now let's delete the loaded topic documents in the Vector Store.

In [22]:
del vector_store

In [23]:
small_med_df.to_csv('./small_med_df.csv', index=False)
docs = CSVLoader('./small_med_df.csv').load()
print(docs[:5])

[Document(metadata={'source': './small_med_df.csv', 'row': 0}, page_content="question: What is (are) Diabetes ?\nanswer: Too Much Glucose in the Blood Diabetes means your blood glucose (often called blood sugar) is too high. Your blood always has some glucose in it because your body needs glucose for energy to keep you going. But too much glucose in the blood isn't good for your health. Glucose comes from the food you eat and is also made in your liver and muscles. Your blood carries the glucose to all of the cells in your body. Insulin is a chemical (a hormone) made by the pancreas. The pancreas releases insulin into the blood. Insulin helps the glucose from food get into your cells. If your body does not make enough insulin or if the insulin doesn't work the way it should, glucose can't get into your cells. It stays in your blood instead. Your blood glucose level then gets too high, causing pre-diabetes or diabetes. Types of Diabetes There are three main kinds of diabetes: type 1, type 2, and gestational diabetes. The result of type 1 and type 2 diabetes is the same: glucose builds up in the blood, while the cells are starved of energy. Over the years, high blood glucose damages nerves and blood vessels, oftentimes leading to complications such as heart disease, stroke, blindness, kidney disease, nerve problems, gum infections, and amputation. Type 1 Diabetes Type 1 diabetes, which used to be called called juvenile diabetes or insulin-dependent diabetes, develops most often in young people. However, type 1 diabetes can also develop in adults. With this form of diabetes, your body no longer makes insulin or doesnt make enough insulin because your immune system has attacked and destroyed the insulin-producing cells. About 5 to 10 percent of people with diabetes have type 1 diabetes. To survive, people with type 1 diabetes must have insulin delivered by injection or a pump. Learn more about type 1 diabetes here. Type 2 Diabetes Type 2 diabetes, which used to be called adult-onset diabetes or non insulin-dependent diabetes, is the most common form of diabetes. Although people can develop type 2 diabetes at any age -- even during childhood -- type 2 diabetes develops most often in middle-aged and older people. Type 2 diabetes usually begins with insulin resistancea condition that occurs when fat, muscle, and liver cells do not use insulin to carry glucose into the bodys cells to use for energy. As a result, the body needs more insulin to help glucose enter cells. At first, the pancreas keeps up with the added demand by making more insulin. Over time, the pancreas doesnt make enough insulin when blood sugar levels increase, such as after meals. If your pancreas can no longer make enough insulin, you will need to treat your type 2 diabetes. Learn more about type 2 diabetes here. Gestational Diabetes Some women develop gestational diabetes during the late stages of pregnancy. Gestational diabetes is caused by the hormones of pregnancy or a shortage of insulin. Although this form of diabetes usually goes away after the baby is born, a woman who has had it and her child are more likely to develop diabetes later in life. Prediabetes Prediabetes means your blood glucose levels are higher than normal but not high enough for a diagnosis of diabetes. People with prediabetes are at an increased risk for developing type 2 diabetes and for heart disease and stroke. The good news is that if you have prediabetes, you can reduce your risk of getting type 2 diabetes. With modest weight loss and moderate physical activity, you can delay or prevent type 2 diabetes.  Learn more about prediabetes here.  Signs of Diabetes Many people with diabetes experience one or more symptoms, including extreme thirst or hunger, a frequent need to urinate and/or fatigue. Some lose weight without trying. Additional signs include sores that heal slowly, dry, itchy skin, loss of feeling or tingling in the feet and blurry eyesight. Some people with diabetes, however, have no symptoms at all. How Many Have Diabetes? Nearly 29 million Americans age 20 or older (12.3 percent of all people in this age group) have diabetes, according to 2014 estimates from the Centers for Disease Control and Prevention (CDC). About 1.9 million people aged 20 years or older were newly diagnosed with diabetes in 2010 alone. People can get diabetes at any age, but the risk increases as we get older. In 2014, over 11 million older adults living in the U.S -- nearly 26 percent of people 65 or older -- had diabetes. See more statistics about diabetes from the  National Diabetes Statistics Report 2014. (Centers for Disease Control and Prevention.) If Diabetes is Not Managed Diabetes is a very serious disease. Over time, diabetes that is not well managed causes serious damage to the eyes, kidneys, nerves, heart, gums and teeth. If you have diabetes, you are more likely than people without diabetes to have heart disease or a stroke. People with diabetes also tend to develop heart disease or stroke at an earlier age than others. The best way to protect yourself from the serious complications of diabetes is to manage your blood glucose, blood pressure and cholesterol and to avoid smoking. It is not always easy, but people who make an ongoing effort to manage their diabetes can greatly improve their overall health.\nsource: NIHSeniorHealth\nfocus_area: Diabetes"), Document(metadata={'source': './small_med_df.csv', 'row': 1}, page_content="question: Who is at risk for Diabetes? ?\nanswer: Diabetes is a serious, life-long disease. It can lead to problems such as heart disease, stroke, vision loss, kidney disease, and nerve damage. More than 8 million people in the United States have type 2 diabetes and dont know it. Many people dont find out they have diabetes until they are faced with problems such as blurry vision or heart trouble. Certain factors can increase your risk for diabetes, and its important to know what they are. Type 1 Diabetes Type 1 diabetes is an autoimmune disease. In an autoimmune reaction, antibodies, or immune cells, attach to the bodys own healthy tissues by mistake, signaling the body to attack them. At present, scientists do not know exactly what causes the body's immune system to attack the cells, but many believe that both genetic factors and environmental factors, such as viruses, are involved. Studies are now underway to identify these factors and prevent type 1 diabetes in people at risk.  Learn more about the causes of type 1 diabetes.  Type 2 Diabetes Type 2 diabetes -- the most common form -- is linked closely to overweight and obesity, high blood pressure, and abnormal cholesterol levels. Many people with type 2 diabetes are overweight. Being overweight can keep your body from using insulin properly. Genes also play an important role in a person's risk for type 2 diabetes. Having certain genes or combinations of genes may increase or decrease a persons risk for developing the disease.  Here are the risk factors for type 2 diabetes. -  being over 45 years of age  -  being overweight or obese  - having a first-degree relative -- a parent, brother, or sister -- with diabetes  - being African American, American Indian or Alaska Native, Asian American or Pacific Islander, or Hispanic American/Latino. (Watch the video to learn more about native Americans and diabetes risk. To enlarge the video, click the brackets in the lower right-hand corner. To reduce the video, press the Escape (Esc) button on your keyboard.) being over 45 years of age being overweight or obese having a first-degree relative -- a parent, brother, or sister -- with diabetes being African American, American Indian or Alaska Native, Asian American or Pacific Islander, or Hispanic American/Latino. (Watch the video to learn more about native Americans and diabetes risk. To enlarge the video, click the brackets in the lower right-hand corner. To reduce the video, press the Escape (Esc) button on your keyboard.) - having gestational diabetes, or giving birth to at least one baby weighing more than 9 pounds  - having blood pressure of 140/90 or higher, or having been told that you have high blood pressure.  - having abnormal cholesterol levels -- an HDL cholesterol level of 35 or lower, or a triglyceride level of 250 or higher  - being inactive or exercising fewer than three times a week.  - having polycystic ovary syndrome, also called PCOS (women only)  - on previous testing, having prediabetes (an A1C level of 5.7 to 6.4 percent), impaired glucose tolerance (IGT) or impaired fasting glucose (IFG)  - history of cardiovascular disease (disease affecting the heart and blood vessels). having gestational diabetes, or giving birth to at least one baby weighing more than 9 pounds having blood pressure of 140/90 or higher, or having been told that you have high blood pressure. having abnormal cholesterol levels -- an HDL cholesterol level of 35 or lower, or a triglyceride level of 250 or higher being inactive or exercising fewer than three times a week. having polycystic ovary syndrome, also called PCOS (women only) on previous testing, having prediabetes (an A1C level of 5.7 to 6.4 percent), impaired glucose tolerance (IGT) or impaired fasting glucose (IFG) history of cardiovascular disease (disease affecting the heart and blood vessels).  Learn more about the causes of type 2 diabetes.  Prediabetes and Type 2 Diabetes Before people develop type 2 diabetes, they usually have prediabetes -- a condition in which blood glucose levels are higher than normal, but not high enough for a diagnosis of diabetes. People with prediabetes are more likely to develop diabetes within 10 years and also are more likely to have a heart attack or stroke. Prediabetes is increasingly common in the U.S. adult population. In 2012, about 86 million people in the U.S. had pre-diabetes, and 51% of those 65 or older had prediabetes. Learn more about prediabetes.  Gestational Diabetes Some women develop diabetes during the late stages of pregnancy. This is called gestational diabetes. Although this form of diabetes usually goes away after the baby is born, a woman who has had it has a lifelong risk for developing diabetes, mostly type 2.\nsource: NIHSeniorHealth\nfocus_area: Diabetes"), Document(metadata={'source': './small_med_df.csv', 'row': 2}, page_content='question: How to prevent Diabetes ?\nanswer: The two most common forms of diabetes are type 1 and type 2. Currently, there is no way to delay or prevent type 1 diabetes. However, research has shown that type 2 diabetes can be prevented or delayed in people at risk for the disease. Preventing type 2 diabetes can mean a healthier and longer life without serious complications from the disease such as heart disease, stroke, blindness, kidney failure, and amputations. Preventing Type 2 Diabetes Before people develop type 2 diabetes, they usually have prediabetes -- a condition in which blood glucose levels are higher than normal, but not yet high enough for a diagnosis of diabetes. The good news is that if you have prediabetes, there are ways to reduce your risk of getting type 2 diabetes. With modest weight loss and moderate physical activity, you can delay or prevent type 2 diabetes Benefits of Weight Loss and Exercise  The Diabetes Prevention Program (DPP) is a landmark study by the National Institute of Diabetes and Digestive and Kidney Diseases. DPP researchers found that adults at high risk for type 2 diabetes were able to cut their risk in half by losing a modest amount of weight and being active almost every day. This means losing 5 to 7 percent of body weight (that\'s 10 pounds if you weigh 200 pounds) and getting 150 minutes of physical activity a week. The drug metformin reduced the risk of type 2 diabetes by 34 percent but was more effective in younger and heavier adults. (Watch the video to learn more about preventing type 2 diabetes. To enlarge the video, click the brackets in the lower right-hand corner. To reduce the video, press the Escape (Esc) button on your keyboard.) The benefits of weight loss and regular exercise have long-lasting value. In a DPP follow-up trial known as the Diabetes Prevention Program Outcome Study (DPPOS), people at risk of type 2 diabetes who kept off the weight they had lost and who continued to exercise regularly delayed the onset of type 2 diabetes by about 4 years. The DPP study also showed that modest weight loss (achieved by following a low calorie, low-fat diet) and moderate physical activity were especially effective in preventing or delaying the development of diabetes in older people. In fact, people over the age of 60 were able to reduce their risk for developing type 2 diabetes by 71 percent. How to Lower Your Risk Making modest lifestyle changes can help prevent or delay type 2 diabetes in people who are at risk. Here are some tips. Reach and Maintain a Reasonable Body Weight Your weight affects your health in many ways. Being overweight can keep your body from making and using insulin properly. It can also cause high blood pressure. The Body Mass Index chart  (seen here) can be used to find out whether someone is normal weight, overweight, or obese. Body mass index is a measurement of body weight relative to height for adults age 20 or older. To use the chart -  find the person\'s height in the left-hand column   -  move across the row to find the number closest to the person\'s weight   -  find the number at the top of that column   - The number at the top of the column is the persons BMI. find the person\'s height in the left-hand column move across the row to find the number closest to the person\'s weight find the number at the top of that column The number at the top of the column is the persons BMI. The words above the BMI number indicate whether the person is normal weight, overweight, or obese. People who are overweight or obese should consider talking with a health care provider about ways to lose weight and reduce the risk of diabetes. The BMI has certain limitations. The BMI may overestimate body fat in athletes and others who have a muscular build and underestimate body fat in older adults and others who have lost muscle.  Waist Measurement. In addition to weight, the location of excess fat on the body can be important. A waist measurement of 40 inches or more for men and 35 inches or more for women is linked to insulin resistance and increases a persons risk for type 2 diabetes. This is true even if a persons body mass index (BMI) falls within the normal range. To measure the waist, a person should - place a tape measure around the bare abdomen just above the hip bone  - make sure the tape is snug but isnt digging into the skin and is parallel to the floor  - relax, exhale, and measure. place a tape measure around the bare abdomen just above the hip bone make sure the tape is snug but isnt digging into the skin and is parallel to the floor relax, exhale, and measure. Make Healthy Food Choices What you eat has a big impact on your weight and overall health. By developing healthy eating habits, you can help manage your body weight, blood pressure, and cholesterol. Reducing portion size, increasing the amount of fiber you consume (by eating more fruits and vegetables) and limiting fatty and salty foods are key to a healthy diet. Here are more tips for eating well with diabetes. - Make a diabetes meal plan with help from your health care team.   - Choose foods that are lower in calories, saturated fat, trans fat, sugar, and salt.   - Eat foods with more fiber, such as whole grain cereals, breads, crackers, rice, or pasta.   - Choose foods such as fruits, vegetables, whole grains, bread and cereals, and low-fat or skim milk and cheese.   - Drink water instead of juice and regular soda.   - When eating a meal, fill half of your plate with fruits and vegetables, one quarter with a lean protein, such as beans, or chicken or turkey without the skin, and one quarter with a whole grain, such as brown rice or whole wheat pasta. Make a diabetes meal plan with help from your health care team. Choose foods that are lower in calories, saturated fat, trans fat, sugar, and salt. Eat foods with more fiber, such as whole grain cereals, breads, crackers, rice, or pasta. Choose foods such as fruits, vegetables, whole grains, bread and cereals, and low-fat or skim milk and cheese. Drink water instead of juice and regular soda. When eating a meal, fill half of your plate with fruits and vegetables, one quarter with a lean protein, such as beans, or chicken or turkey without the skin, and one quarter with a whole grain, such as brown rice or whole wheat pasta. For more about healthy eating and older adults see  "Eating Well as You Get Older." Be Physically Active Get at least 30 minutes of exercise at least five days a week. Regular exercise reduces diabetes risk in several ways. It - helps you lose weight  - controls your cholesterol and blood pressure  -  improves your body\'s use of insulin.  helps you lose weight controls your cholesterol and blood pressure improves your body\'s use of insulin. Many people make walking part of their daily routine because its easy, fun and convenient. But you can choose any activity that gets you moving. Its fine to break up your 30 minutes of exercise into smaller increments, such as three 10-minute periods. Check with your doctor before beginning any exercise program. Many people make walking part of their daily routine because its easy, fun and convenient. But you can choose any activity that gets you moving. Its fine to break up your 30 minutes of exercise into smaller increments, such as three 10-minute periods. Check with your doctor before beginning any exercise program. For more information on exercise and older adults, see  Exercises to Try or visit Go4Life, the exercise and physical activity campaign for older adults from the National Institute on Aging.\nsource: NIHSeniorHealth\nfocus_area: Diabetes'), Document(metadata={'source': './small_med_df.csv', 'row': 3}, page_content='question: What are the symptoms of Diabetes ?\nanswer: Diabetes is often called a "silent" disease because it can cause serious complications even before you have symptoms. Symptoms can also be so mild that you dont notice them. An estimated 8 million people in the United States have type 2 diabetes and dont know it, according to 2012 estimates by the Centers for Disease Control and Prevention (CDC). Common Signs Some common symptoms of diabetes are: - being very thirsty  - frequent urination  - feeling very hungry or tired  - losing weight without trying  - having sores that heal slowly  - having dry, itchy skin  - loss of feeling or tingling in the feet  - having blurry eyesight. being very thirsty frequent urination feeling very hungry or tired losing weight without trying having sores that heal slowly having dry, itchy skin loss of feeling or tingling in the feet having blurry eyesight. Signs of type 1 diabetes usually develop over a short period of time. The signs for type 2 diabetes develop more gradually. Tests for Diabetes The following tests are used to diagnose diabetes or prediabetes. - An A1C test measures your average blood glucose levels over the past 3 months. It can be used to diagnose type 2 diabetes and prediabetes. It does not require fasting and blood can be drawn for the test any time of the day.  An A1C test measures your average blood glucose levels over the past 3 months. It can be used to diagnose type 2 diabetes and prediabetes. It does not require fasting and blood can be drawn for the test any time of the day. - A fasting plasma glucose, or FPG test, measures your blood glucose after you have gone at least 8 hours without eating. Doctors use this test to detect diabetes or prediabetes.  A fasting plasma glucose, or FPG test, measures your blood glucose after you have gone at least 8 hours without eating. Doctors use this test to detect diabetes or prediabetes. - In a random plasma glucose t

## 2.0.0 Load the Question and Answer values as documents into the Vector Database

In [ ]:
df = pd.DataFrame.from_dict({'focus_area': focus_areas})
df.to_csv('../data//focus_areas.csv', index=False)
docs = CSVLoader('../data/focus_areas.csv').load()
print(docs[:5])

[Document(metadata={'source': '../data/focus_areas.csv', 'row': 0}, page_content='focus_area: 11-beta-hydroxylase deficiency'), Document(metadata={'source': '../data/focus_areas.csv', 'row': 1}, page_content='focus_area: 15q11.2 microdeletion'), Document(metadata={'source': '../data/focus_areas.csv', 'row': 2}, page_content='focus_area: 15q13.3 microdeletion'), Document(metadata={'source': '../data/focus_areas.csv', 'row': 3}, page_content='focus_area: 15q13.3 microdeletion syndrome'), Document(metadata={'source': '../data/focus_areas.csv', 'row': 4}, page_content='focus_area: 15q13.3 microduplication syndrome')]

In [25]:
vector_store = QdrantVectorStore.from_documents(
    docs,
    embeddings,
    url=os.environ['QDRANT_URL'],
    prefer_grpc=True,
    api_key=os.environ['QDRANT_API_KEY'],
    collection_name="test",
)

In [32]:
docs = vector_store.similarity_search("What is type 1 diabetes?", k=2)
for doc in docs:
    print(doc)

page_content='focus_area: type 1 diabetes' metadata={'source': '../data/focus_areas.csv', 'row': 5108, '_id': 'e2751373-f497-4efa-9829-69d61d065e67', '_collection_name': 'test'}
page_content='focus_area: Diabetes Type 1' metadata={'source': '../data/focus_areas.csv', 'row': 1186, '_id': '16897d25-874d-4023-a4fb-d2e9f51a3f9d', '_collection_name': 'test'}

In [33]:
del vector_store

In [34]:
docs = CSVLoader('../data/medquad.csv').load()
print(docs[:5])

[Document(metadata={'source': '../data/medquad.csv', 'row': 0}, page_content="question: What is (are) Glaucoma ?\nanswer: Glaucoma is a group of diseases that can damage the eye's optic nerve and result in vision loss and blindness. While glaucoma can strike anyone, the risk is much greater for people over 60. How Glaucoma Develops  There are several different types of glaucoma. Most of these involve the drainage system within the eye. At the front of the eye there is a small space called the anterior chamber. A clear fluid flows through this chamber and bathes and nourishes the nearby tissues. (Watch the video to learn more about glaucoma. To enlarge the video, click the brackets in the lower right-hand corner. To reduce the video, press the Escape (Esc) button on your keyboard.) In glaucoma, for still unknown reasons, the fluid drains too slowly out of the eye. As the fluid builds up, the pressure inside the eye rises. Unless this pressure is controlled, it may cause damage to the optic nerve and other parts of the eye and result in loss of vision. Open-angle Glaucoma The most common type of glaucoma is called open-angle glaucoma. In the normal eye, the clear fluid leaves the anterior chamber at the open angle where the cornea and iris meet. When fluid reaches the angle, it flows through a spongy meshwork, like a drain, and leaves the eye. Sometimes, when the fluid reaches the angle, it passes too slowly through the meshwork drain, causing the pressure inside the eye to build. If the pressure damages the optic nerve, open-angle glaucoma -- and vision loss -- may result. There is no cure for glaucoma. Vision lost from the disease cannot be restored. However, there are treatments that may save remaining vision. That is why early diagnosis is important.  See this graphic for a quick overview of glaucoma,  including how many people it affects, whos at risk, what to do if you have it, and how to learn more.  See a glossary of glaucoma terms.\nsource: NIHSeniorHealth\nfocus_area: Glaucoma"), Document(metadata={'source': '../data/medquad.csv', 'row': 1}, page_content='question: What causes Glaucoma ?\nanswer: Nearly 2.7 million people have glaucoma, a leading cause of blindness in the United States. Although anyone can get glaucoma, some people are at higher risk. They include - African-Americans over age 40  - everyone over age 60, especially Hispanics/Latinos  - people with a family history of glaucoma. African-Americans over age 40 everyone over age 60, especially Hispanics/Latinos people with a family history of glaucoma.  In addition to age, eye pressure is a risk factor. Whether you develop glaucoma depends on the level of pressure your optic nerve can tolerate without being damaged. This level is different for each person. Thats why a comprehensive dilated eye exam is very important. It can help your eye care professional determine what level of eye pressure is normal for you. Another risk factor for optic nerve damage relates to blood pressure. Thus, it is important to also make sure that your blood pressure is at a proper level for your body by working with your medical doctor. (Watch the animated video to learn more about the causes of glaucoma. To enlarge the video, click the brackets in the lower right-hand corner. To reduce the video, press the Escape (Esc) button on your keyboard.)\nsource: NIHSeniorHealth\nfocus_area: Glaucoma'), Document(metadata={'source': '../data/medquad.csv', 'row': 2}, page_content='question: What are the symptoms of Glaucoma ?\nanswer: Symptoms of Glaucoma  Glaucoma can develop in one or both eyes. The most common type of glaucoma, open-angle glaucoma, has no symptoms at first. It causes no pain, and vision seems normal. Without treatment, people with glaucoma will slowly lose their peripheral, or side vision. They seem to be looking through a tunnel. Over time, straight-ahead vision may decrease until no vision remains. Tests for Glaucoma Glaucoma is detected through a comprehensive eye exam that includes a visual acuity test, visual field test, dilated eye exam, tonometry, and pachymetry. (Watch the animated video to learn more about testing for glaucoma. To enlarge the video, click the brackets in the lower right-hand corner. To reduce the video, press the Escape (Esc) button on your keyboard.)  A visual acuity test uses an eye chart test to measure how well you see at various distances. A visual field test measures your side or peripheral vision. It helps your eye care professional tell if you have lost side vision, a sign of glaucoma. In a dilated eye exam, drops are placed in your eyes to widen, or dilate, the pupils. Your eye care professional uses a special magnifying lens to examine your retina and optic nerve for signs of damage and other eye problems. After the exam, your close-up vision may remain blurred for several hours. In tonometry, an instrument measures the pressure inside the eye. Numbing drops may be applied to your eye for this test. With pachymetry,  a numbing drop is applied to your eye. Your eye care professional uses an ultrasonic wave instrument to measure the thickness of your cornea.\nsource: NIHSeniorHealth\nfocus_area: Glaucoma'), Document(metadata={'source': '../data/medquad.csv', 'row': 3}, page_content='question: What are the treatments for Glaucoma ?\nanswer: Although open-angle glaucoma cannot be cured, it can usually be controlled. While treatments may save remaining vision, they do not improve sight already lost from glaucoma. The most common treatments for glaucoma are medication and surgery. Medications  Medications for glaucoma may be either in the form of eye drops or pills. Some drugs reduce pressure by slowing the flow of fluid into the eye. Others help to improve fluid drainage. (Watch the video to learn more about coping with glaucoma. To enlarge the video, click the brackets in the lower right-hand corner. To reduce the video, press the Escape (Esc) button on your keyboard.) For most people with glaucoma, regular use of medications will control the increased fluid pressure. But, these drugs may stop working over time. Or, they may cause side effects. If a problem occurs, the eye care professional may select other drugs, change the dose, or suggest other ways to deal with the problem.  Read or listen to ways some patients are coping with glaucoma. Surgery Laser surgery is another treatment for glaucoma. During laser surgery, a strong beam of light is focused on the part of the anterior chamber where the fluid leaves the eye. This results in a series of small changes that makes it easier for fluid to exit the eye. Over time, the effect of laser surgery may wear off. Patients who have this form of surgery may need to keep taking glaucoma drugs. Researching Causes and Treatments Through studies in the laboratory and with patients, NEI is seeking better ways to detect, treat, and prevent vision loss in people with glaucoma. For example, researchers have discovered genes that could help explain how glaucoma damages the eye. NEI also is supporting studies to learn more about who is likely to get glaucoma, when to treat people who have increased eye pressure, and which treatment to use first.\nsource: NIHSeniorHealth\nfocus_area: Glaucoma'), Document(metadata={'source': '../data/medquad.csv', 'row': 4}, page_content="question: What is (are) Glaucoma ?\nanswer: Glaucoma is a group of diseases that can damage the eye's optic nerve and result in vision loss and blindness. The most common form of the disease is open-angle glaucoma. With early treatment, you can often protect your eyes against serious vision loss. (Watch the video to learn more about glaucoma. To enlarge the video, click the brackets in the lower right-hand corner. To reduce the video, press the Escape (Esc) button on your keyboard.)  See this graphic for a quick overview of glaucoma, including how many people it affects, whos at risk, what to do if you have it, and how to learn more.  See a glossary of glaucoma terms.\nsource: NIHSeniorHealth\nfocus_area: Glaucoma")]

In [ ]:
# vector_store = QdrantVectorStore.from_documents(
#     docs,
#     embeddings,
#     url=os.environ['QDRANT_URL'],
#     prefer_grpc=True,
#     api_key=os.environ['QDRANT_API_KEY'],
#     collection_name="medquad",
# )

In [ ]:
# del vector_store

In [40]:
docs = vector_store.similarity_search("What is type 1 diabetes?", k=2)
for doc in docs:
    print(doc)

page_content='question: What is (are) Diabetes mellitus type 1 ?
answer: Diabetes mellitus type 1 (DM1) is a condition in which cells in the pancreas (beta cells) stop producing insulin, causing abnormally high blood sugar levels. Lack of insulin results in the inability of the body to use glucose for energy and control the amount of sugar in the blood. DM1 can occur at any age, but usually develops by early adulthood, most often in adolescence. Symptoms of high blood sugar may include frequent urination, excessive thirst, fatigue, blurred vision, tingling or loss of feeling in the hands and feet, and weight loss. The exact cause of DM1 is unknown, but having certain "variants" of specific genes may increase a person's risk to develop the condition. A predisposition to develop DM1 runs in families, but no known inheritance pattern exists. Treatment includes blood sugar control and insulin replacement therapy. Improper control can cause recurrence of high blood sugar, or abnormally low blood sugar (hypoglycemia) during exercise or when eating is delayed. If not treated, the condition can be life-threatening. Over many years, chronic high blood sugar may be associated with a variety of complications that affect many parts of the body.
source: GARD
focus_area: Diabetes mellitus type 1' metadata={'source': '../data/medquad.csv', 'row': 2702, '_id': '3be2e104-844d-4d5a-b79a-8c2490a8e24f', '_collection_name': 'medquad'}
page_content='question: What is (are) type 1 diabetes ?
answer: Type 1 diabetes is a disorder characterized by abnormally high blood sugar levels. In this form of diabetes, specialized cells in the pancreas called beta cells stop producing insulin. Insulin controls how much glucose (a type of sugar) is passed from the blood into cells for conversion to energy. Lack of insulin results in the inability to use glucose for energy or to control the amount of sugar in the blood.  Type 1 diabetes can occur at any age; however, it usually develops by early adulthood, most often starting in adolescence. The first signs and symptoms of the disorder are caused by high blood sugar and may include frequent urination (polyuria), excessive thirst (polydipsia), fatigue, blurred vision, tingling or loss of feeling in the hands and feet, and weight loss. These symptoms may recur during the course of the disorder if blood sugar is not well controlled by insulin replacement therapy. Improper control can also cause blood sugar levels to become too low (hypoglycemia). This may occur when the body's needs change, such as during exercise or if eating is delayed. Hypoglycemia can cause headache, dizziness, hunger, shaking, sweating, weakness, and agitation.  Uncontrolled type 1 diabetes can lead to a life-threatening complication called diabetic ketoacidosis. Without insulin, cells cannot take in glucose. A lack of glucose in cells prompts the liver to try to compensate by releasing more glucose into the blood, and blood sugar can become extremely high. The cells, unable to use the glucose in the blood for energy, respond by using fats instead. Breaking down fats to obtain energy produces waste products called ketones, which can build up to toxic levels in people with type 1 diabetes, resulting in diabetic ketoacidosis. Affected individuals may begin breathing rapidly; develop a fruity odor in the breath; and experience nausea, vomiting, facial flushing, stomach pain, and dryness of the mouth (xerostomia). In severe cases, diabetic ketoacidosis can lead to coma and death.  Over many years, the chronic high blood sugar associated with diabetes may cause damage to blood vessels and nerves, leading to complications affecting many organs and tissues. The retina, which is the light-sensitive tissue at the back of the eye, can be damaged (diabetic retinopathy), leading to vision loss and eventual blindness. Kidney damage (diabetic nephropathy) may also occur and can lead to kidney failure and end-stage renal disease (ESRD). Pain, tingling, and loss of normal sensation (diabetic neuropathy) often occur, especially in the feet. Impaired circulation and absence of the normal sensations that prompt reaction to injury can result in permanent damage to the feet; in severe cases, the damage can lead to amputation. People with type 1 diabetes are also at increased risk of heart attacks, strokes, and problems with urinary and sexual function.
source: GHR
focus_area: type 1 diabetes' metadata={'row': 10740, 'source': '../data/medquad.csv', '_id': '760a421d-f4e7-45b5-a2e6-b74255ea2b2e', '_collection_name': 'medquad'}

In [9]:
vector_store = QdrantVectorStore.from_existing_collection(
    embedding=embeddings,
    collection_name="medquad",
    url=os.environ['QDRANT_URL'],
    api_key=os.environ['QDRANT_API_KEY'],
)

# 2.1 Generate RAG prompt with context

In [ ]:
from pydantic import BaseModel
from typing import List, Dict, Optional

# from langchain import hub
from langchain_core.documents import Document
from langchain_core.vectorstores import VectorStore
from langchain_core.prompts import PromptTemplate

# prompt = hub.pull("rlm/rag-prompt")
# print("System Prompt we are using: ")
# print(prompt.messages[0].prompt.template)

SYSTEM_PROMPT = """
You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. 
If you don't know the answer, just say that you don't know. Keep the answer short and concise. Try to use less than 5 sentences.
"""
PROMPT_TEMPLATE = SYSTEM_PROMPT + """
Question: {question} 
Context: {context} 
Answer: 
"""
prompt = PromptTemplate.from_template(PROMPT_TEMPLATE)

class State(BaseModel):
    question: str
    context: Optional[List[Document]]
    answer: str
    tenant: Optional[str]


def retrieve(db: VectorStore, state: State):
    # defaults to k = 4, so max 4 documents are returned.
    retrieved_docs = db.similarity_search(state.question)
    return {"context": retrieved_docs}


def generate(state: State):
    if state.context is None:
        state.context = []
    docs_content = "\n\n".join(doc.page_content for doc in state.context)
    messages = prompt.invoke(
        {"question": state.question, "context": docs_content})
    response = llm.invoke(messages)
    return {"answer": response.content}


def retrieve_and_generate(user_prompt, tenant=None):
    state = State(question=user_prompt, context=None, answer='', tenant=None)
    if tenant:
        state.tenant = tenant

    context = retrieve(vector_store, state)
    state.context = context['context']

    ans = generate(state)['answer']
    return ans


def print_rag(user_prompt, rag_answer):
    print("User: \n{}".format(user_prompt))
    print()
    print("Answer: \n{}".format(rag_answer))


def print_rag2(user_prompt, rag_answer):
    print("Question: \t{}".format(user_prompt))
    print("Answer: \t{}".format(rag_answer))


def print_rag3(user_prompt, rag_answer):
    tmp_df = pd.DataFrame.from_dict(
        {'User': [user_prompt], 'RAG AI Response': [rag_answer]})
    with pd.option_context('display.max_colwidth', None, "colheader_justify", "left"):
        display(tmp_df)
    return tmp_df

System Prompt we are using:
You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise.
Question: {question}
Context: {context}
Answer:

# 2.2 Ask Questions

In [12]:
ques = "Tell me about the types of diabetes..."
ans = retrieve_and_generate(ques)
print_rag(ques, ans)

User:
Tell me about the types of diabetes...

Answer:
The main types of diabetes include type 1, type 2, and gestational diabetes. Type 1 diabetes is an autoimmune condition where the body does not produce insulin, while type 2 is characterized by insulin resistance and is more common, often linked to lifestyle factors. Gestational diabetes occurs during pregnancy and typically resolves after childbirth, though it can increase the risk of developing type 2 diabetes later on.

## Pain point 1: Retrieval Configuration
The Policy/Configuration for retrieval, defining things such as how many document are returned, can greatly affect the output.

Imagine there were 30 types of diabetes, and our Q&A dataset did not contain any documents which mentioned them. Only individual documents which talk about individual types of diabetes.

Our Vector DB Search yields 4 documents as a good middle ground between returning too few documents and too many, making the prompt very long, possibly long enough that the question is "forgotten".

Data that's provided to the RAG system matters a lot!

Configuration that's used matters a lot!

## Pain point 2: Evaluation and Improvement 

Is this RAG good enough?

How do you determine that?

I'm learning about this topic, and I'll keep sharing any knowledge or resources I come across in my notebooks.

## Pain point 3: Processing Unstructured Data

In this case, the dataset is highly structured, and we have high quality data -- question and answer pairs.

This makes our life easy, but if we had an unstructured dataset, we would have to do a lot of clean-up, NER, summarization, classification, etc.

If we wanted to create Question and Answer pairs from Doctor's notes where patients asked questions and an AI transcribed the visit live, we would need to do many of the steps mentioned above.

In [23]:
ques = "I eat too much fried food, is that bad?"
ans = retrieve_and_generate(ques)
print_rag(ques, ans)

User:
I eat too much fried food, is that bad?

Answer:
Yes, eating too much fried food can be bad for your health, as it often contains unhealthy fats, particularly trans fats, which can raise cholesterol levels and increase the risk of heart disease. It is important to consider healthier fat options and moderation in your diet. Reducing fried foods can help improve your overall health and decrease the risk of related conditions.

In [24]:
ques = "How much water should a person drink in a day?"
ans = retrieve_and_generate(ques)
print_rag(ques, ans)

User:
How much water should a person drink in a day?

Answer:
An average person needs about 3 quarts of water daily, but this can vary based on activity level and environmental conditions. It's important for individuals, especially elderly and young children, to monitor their fluid intake more closely. Those on hemodialysis should consult with their dietitian for personalized fluid allowances.

## RAG is too easy?

The easy part is what's done in this notebook.

The hard part is Retrieval configuration, Processing Data, and setting up evaluation pipelines, metrics logging, etc.

Making decisions when taking your product to market and reacting to how your clients use the product.

Being Agile is important.

In [25]:
ques = "Can you prescribe me some medicine for my stomach ulcer?"
ans = retrieve_and_generate(ques)
print_rag(ques, ans)

User:
Can you prescribe me some medicine for my stomach ulcer?

Answer:
I can't prescribe medicine, but it's important to see a doctor for proper evaluation and treatment for your stomach ulcer. Common treatments for ulcers typically include medications that reduce stomach acid and promote healing. Over-the-counter options may not be sufficient for more serious conditions like peptic ulcers.

## Uh-oh
Luckily OpenAI's models have been taught to not prescribe medicines, lest someone sue them over it.

But, if you used an open source LLM, you might need to engineer your prompts and use other techniques to prevent Level 1 easy lawsuits, especially before precedents have been set.

Even a simple "Don't prescribe any medicines under any circumstances" added to the system prompt might work.

Cestonaro C, Delicati A, Marcante B, Caenazzo L, Tozzo P. Defining medical liability when artificial intelligence is applied on diagnostic algorithms: a systematic review. Front Med (Lausanne). 2023 Nov 27;10:1305756. doi: 10.3389/fmed.2023.1305756. PMID: 38089864; PMCID: PMC10711067.
https://pmc.ncbi.nlm.nih.gov/articles/PMC10711067/#S5

## Domain Knowledge

Domain knowledge will be important to figure out what's acceptable for the AI to output, and what's not.

Understanding industry specific jargon will also allow data engineers to better pre-process the input data.

In [26]:
ques = "What is wasting?"
ans = retrieve_and_generate(ques)
print_rag(ques, ans)

User:
What is wasting?

Answer:
Wasting is a form of malnutrition characterized by significant weight loss and muscle wasting, often due to inadequate nutrition or illness. It typically suggests a severe lack of essential nutrients and energy, and can lead to serious health complications. Addressing the underlying causes and restoring proper nutrition are crucial for recovery.

## Retrieval Augmented Generation Challenges
In general for domain specific RAG (some of these may apply to this dataset).

### Retrieval Component
- Relevance of retrieved documents
    - Issue: Irrelevant or outdated medical literature or answers.
    - Causes: Weak embedding models, Synonym mismatches like "heart attack" vs. "myocardial infarction", outdated knowledge like "saturated fats are bad for you" without any nuance.
    - Mitigation: Domain specific embeddings (like those used in BioBERT or ClinicalBERT), expanding queries with synonyms, regularly updating knowledge base.
- Coverage
    - Issue: Gaps in the database, or biases in source data.
    - Mitigation: Audit the dataset for diversity in information and inclusion of rare diseases etc, Augment with specialized datasets (rare diseases, misconceptions and corrections etc).
### Generation Component
- Hallucinations
    - Issue: Plausible sounding, but incorrect and un-supported claims (inventing drug dosages, inventing drug names etc).
    - Mitigation: Constrain outputs to retrieved sources, Confidence scores to flag un-certain answers, Rule-based checks (dosage ranges).
- Ambiguity
    - Issue: Queries like "What causes fatigue?" could relate to several factors.
    - Mitigation: Implement Follow-up questions, Return ranked diagnoses with probabilities.
### Data Quality & Ethics
- Outdated or conflicting information
    - Issue: Rapidly evolving medical knowledge, Conflicting studies in the database.
    - Mitigation: Flag conflicting evidence and highlight consensus guildelines, Prioritize peer-reviewed sources, and meta-analyses.
- Privacy and Bias
    - Issue: Sensitive patient data in corpus or biased recommendations.
    - Mitigation: De-identify training data, Test for bias (remember Facebook's face recognition AIs which only detected white faces? That was due to lack of training data for POC, given the sources of their data was mostly North America).
### Evaluation Challenges
- Lack of ground truth
- Clinical safety
    - Mitigation: Human-in-the-loop validation for high risk queries, Guardrails to block unsafe outputs (drug interaction checking, ask follow-ups before finalizing prescriptions).

There are more challenges such as user interaction challenges, challenges in how you present the data, scalability etc.

In [27]:
small_med_df.sample(10)

,question,answer,source,focus_area
2276,What is (are) Malabsorption Syndromes ?,Your small intestine does most of the digestin...,MPlusHealthTopics,Malabsorption Syndromes
551,What is (are) High Blood Cholesterol ?,Too much cholesterol in your blood is called h...,NIHSeniorHealth,High Blood Cholesterol
16064,What is (are) Nutrition for Early Chronic Kidn...,"As blood pressure rises, the risk of damage to...",NIDDK,Nutrition for Early Chronic Kidney Disease in ...
16268,What is (are) Diabetic Kidney Disease ?,Diabetes is a complex group of diseases with a...,NIDDK,Diabetic Kidney Disease
2166,What is (are) Health Checkup ?,Regular health exams and tests can help find p...,MPlusHealthTopics,Health Checkup
15769,What to do for Anemia of Inflammation and Chro...,"People with anemia caused by iron, vitamin B12...",NIDDK,Anemia of Inflammation and Chronic Disease
8178,What is (are) Anemia ?,Espaol\n \nAnemia (uh-NEE-me-uh...,NHLBI,Anemia
16322,What to do for What I need to know about Diarr...,"To prevent dehydration when you have diarrhea,...",NIDDK,What I need to know about Diarrhea
15766,What are the symptoms of Anemia of Inflammatio...,Anemia of inflammation and chronic disease typ...,NIDDK,Anemia of Inflammation and Chronic Disease
15765,What causes Anemia of Inflammation and Chronic...,Anemia of inflammation and chronic disease is ...,NIDDK,Anemia of Inflammation and Chronic Disease

## More questions & answers

In [30]:
ques = "How often should I get a health check-up?"
ans = retrieve_and_generate(ques)
print_rag(ques, ans)

User:
How often should I get a health check-up?

Answer:
You should get regular health check-ups, but the frequency depends on your age, health, family history, and lifestyle. For many adults, it's recommended to have a check-up at least once a year. Children should also receive regular check-ups to monitor their development and catch potential issues early.

In [31]:
ques = "I have been feeling weak and dizzy ever since a mosquito bit me a month ago..."
ans = retrieve_and_generate(ques)
print_rag(ques, ans)

User:
I have been feeling weak and dizzy ever since a mosquito bit me a month ago...

Answer:
Feeling weak and dizzy could be indicative of anemia, which commonly presents symptoms such as fatigue, dizziness, and shortness of breath. It's important to consult a healthcare provider for an accurate diagnosis, especially since these symptoms have persisted since the mosquito bite. They can evaluate your condition and determine if there is an underlying issue that needs to be addressed.

In [32]:
ques = "Do you think I could be anemic?"
ans = retrieve_and_generate(ques)
print_rag(ques, ans)

User:
Do you think I could be anemic?

Answer:
If you are experiencing symptoms like fatigue, weakness, or dizziness, it could be a sign of anemia, but only a doctor can diagnose it. They will evaluate your medical history, symptoms, and may conduct tests, such as a complete blood count (CBC), to determine if you are anemic. It's best to consult your healthcare provider for an accurate diagnosis.

In [33]:
ques = "What's a blood count?"
ans = retrieve_and_generate(ques)
print_rag(ques, ans)

User:
What's a blood count?

Answer:
A blood count, specifically a complete blood count (CBC), is a common test used to measure various components of blood, including red blood cells, white blood cells, and platelets. It provides important measurements like hemoglobin and hematocrit levels, which help diagnose conditions like anemia. The CBC can indicate overall health and detect a wide range of disorders, including infections and blood cancers.

In [34]:
ques = "Thanks"
ans = retrieve_and_generate(ques)
print_rag(ques, ans)

User:
Thanks

Answer:
You're welcome! If you have any more questions or need further information, feel free to ask.